{"name": "test_customer_signIn[edge]", "status": "broken", "statusDetails": {"message": "TypeError: Level not an integer or a valid string: None", "trace": "request = <SubRequest 'init_driver' for <Function test_customer_signIn[edge]>>\n\n    @pytest.fixture(params=['edge'], scope='class')\n    def init_driver(request):\n        if request.param == \"edge\":\n>           value = webdriver.Edge(EdgeChromiumDriverManager().install())\n\ntestCases\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\microsoft.py:50: in __init__\n    super().__init__(path, log_level, print_first_line, cache_valid_range)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\manager.py:13: in __init__\n    log(\"====== WebDriver manager ======\", level=log_level)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\logger.py:25: in log\n    _init_logger(level, name, first_line, formatter)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\logger.py:19: in _init_logger\n    _logger.setLevel(level)\nC:\\Program Files (x86)\\Python39\\lib\\logging\\__init__.py:1421: in setLevel\n    self.level = _checkLevel(level)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nlevel = None\n\n    def _checkLevel(level):\n        if isinstance(level, int):\n            rv = level\n        elif str(level) == level:\n            if level not in _nameToLevel:\n                raise ValueError(\"Unknown level: %r\" % level)\n            rv = _nameToLevel[level]\n        else:\n>           raise TypeError(\"Level not an integer or a valid string: %r\" % level)\nE           TypeError: Level not an integer or a valid string: None\n\nC:\\Program Files (x86)\\Python39\\lib\\logging\\__init__.py:201: TypeError"}, "parameters": [{"name": "init_driver", "value": "'edge'"}], "start": 1642605816332, "stop": 1642605816332, "uuid": "e922deb8-c04d-4de0-93c6-8745fb2f9d53", "historyId": "c585e072c0210645023e2a96c76ec875", "testCaseId": "61795a803f78060dfbefbeae26fea2b8", "fullName": "test_customer_signIn.Test_customer_signIn#test_customer_signIn", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "suite", "value": "test_customer_signIn"}, {"name": "subSuite", "value": "Test_customer_signIn"}, {"name": "host", "value": "LAPTOP-ESSL3DDB"}, {"name": "thread", "value": "6708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_customer_signIn"}]}