{"name": "test_register_Customer[edge]", "status": "broken", "statusDetails": {"message": "TypeError: Level not an integer or a valid string: None", "trace": "request = <SubRequest 'init_driver' for <Function test_sign_in[edge]>>\n\n    @pytest.fixture(params=['edge'], scope='class')\n    def init_driver(request):\n        if request.param == \"edge\":\n>           value= webdriver.Edge(EdgeChromiumDriverManager().install())\n\ntestCases\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\microsoft.py:50: in __init__\n    super().__init__(path, log_level, print_first_line, cache_valid_range)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\manager.py:13: in __init__\n    log(\"====== WebDriver manager ======\", level=log_level)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\logger.py:25: in log\n    _init_logger(level, name, first_line, formatter)\n..\\Virtual Environmemts\\New Venv\\lib\\site-packages\\webdriver_manager\\logger.py:19: in _init_logger\n    _logger.setLevel(level)\nC:\\Program Files (x86)\\Python39\\lib\\logging\\__init__.py:1421: in setLevel\n    self.level = _checkLevel(level)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nlevel = None\n\n    def _checkLevel(level):\n        if isinstance(level, int):\n            rv = level\n        elif str(level) == level:\n            if level not in _nameToLevel:\n                raise ValueError(\"Unknown level: %r\" % level)\n            rv = _nameToLevel[level]\n        else:\n>           raise TypeError(\"Level not an integer or a valid string: %r\" % level)\nE           TypeError: Level not an integer or a valid string: None\n\nC:\\Program Files (x86)\\Python39\\lib\\logging\\__init__.py:201: TypeError"}, "parameters": [{"name": "init_driver", "value": "'edge'"}], "start": 1642606204003, "stop": 1642606204003, "uuid": "3036b731-34f8-41c5-afb9-6a2121911e2c", "historyId": "04a1088e5e548a5479949f6910cea286", "testCaseId": "6291f82fde1584fc331f6c55ba05dc07", "fullName": "test_register_customer.Test_register_customer#test_register_Customer", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "suite", "value": "test_register_customer"}, {"name": "subSuite", "value": "Test_register_customer"}, {"name": "host", "value": "LAPTOP-ESSL3DDB"}, {"name": "thread", "value": "15824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_register_customer"}]}